#MySQL Configuration
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/cloudvendor?useSSL=false
#    username: root
#    password: cdac
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  mvc:
#    pathmatch:
#      matching-strategy: ANT_PATH_MATCHER
#
#  #JPA_Settings
#  jpa:
#    hibernate:
#      ddl_auto: update
#    show-sql: true

#H2 Configuration
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true